### ISSUE TITLE
Simulation Error: "no server running on /tmp/tmux-0/default"

### ISSUE THREAD

**Issue by ryne2010** [Twisted-Fields/acorn-precision-farming-rover#30]
After successfully building and starting the two containers and connecting to the vehicle container, I get the following error when attempting to list the processes.

"no server running on /tmp/tmux-0/default"

And subsequently receive the following error when attempting to connect to the main process.

"no sessions"

<img width="1079" alt="Untitled" src="https://github.com/Twisted-Fields/acorn-precision-farming-rover/assets/26776548/c5f51481-5df6-46b6-9971-2f164256f620">

**Comment by merlinran** [comment]
the `tmux` sessions are started by `vehicle/autolaunch_vehicle_sim.sh`. You can manually run the scripts there. Here's the result, so yeah there are some dependency issues 
```
root@docker-desktop:/home/acorn # /home/acorn/vehicle/start_main.sh --sim
Traceback (most recent call last):
  File "/home/acorn/vehicle/master_process.py", line 36, in <module>
    import nvidia_power_process
  File "/home/acorn/vehicle/nvidia_power_process.py", line 30, in <module>
    import RPi.GPIO as GPIO
  File "/usr/local/lib/python3.8/dist-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
root@docker-desktop:/home/acorn # /home/acorn/vehicle/start_motors.sh --simulated_hardware
Traceback (most recent call last):
  File "/home/acorn/vehicle/motors.py", line 34, in <module>
    import corner_actuator
  File "/home/acorn/vehicle/corner_actuator.py", line 36, in <module>
    from odrive.enums import *
ModuleNotFoundError: No module named 'odrive'
```
